name: Process-PSModule

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write

jobs:
  Process-PSModule:
    uses: PSModule/Process-PSModule/.github/workflows/workflow.yml@main
    secrets: inherit
